In [1]:
# 4. Creating Arrays from Lists

In [2]:
import numpy as np

In [8]:
#create - from lists
arr = np.array([1,2,3,4,5, "Cipher Mind"])

print(arr, type(arr), arr.shape, arr.dtype)

arrThree = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9], [10, 11, 12]])

print(arrThree, arrThree.shape)

['1' '2' '3' '4' '5' 'Cipher Mind'] <class 'numpy.ndarray'> (6,) <U21
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
