In [1]:
# 5. Creating Arrays (using built-in methods)

In [2]:
import numpy as np

In [21]:
arr = np.zeros((2, 3))

print(arr, arr.shape, arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3) float64


In [22]:
arr = np.ones((4, 5))

print(arr, arr.shape, arr.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (4, 5) float64


In [23]:
arr = np.full((4, 5), "Cipher Mind")

print(arr, arr.shape, arr.dtype)

[['Cipher Mind' 'Cipher Mind' 'Cipher Mind' 'Cipher Mind' 'Cipher Mind']
 ['Cipher Mind' 'Cipher Mind' 'Cipher Mind' 'Cipher Mind' 'Cipher Mind']
 ['Cipher Mind' 'Cipher Mind' 'Cipher Mind' 'Cipher Mind' 'Cipher Mind']
 ['Cipher Mind' 'Cipher Mind' 'Cipher Mind' 'Cipher Mind' 'Cipher Mind']] (4, 5) <U11


In [24]:
arr = np.ones((4, ))

print(arr, arr.shape, arr.dtype)

[1. 1. 1. 1.] (4,) float64


In [26]:
arr = np.ones(( 5, 1))

print(arr, arr.shape, arr.dtype)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]] (5, 1) float64


In [31]:
arr = np.eye((3))

print(arr, arr.shape, arr.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3) float64


In [32]:
arr = np.arange(2, 9, 3)

print(arr)

[2 5 8]


In [35]:
arr = np.linspace(1, 50, 5)

print(arr)

[ 1.   13.25 25.5  37.75 50.  ]
