In [1]:
# 6. Array Properties

In [2]:
import numpy as np

In [3]:
arr = np.array(([1,2,3,4,5,6,7,8,9,10], [1,2,3,4,5,6,7,8,9,10]))

print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [4]:
print(arr.shape)

(2, 10)


In [5]:
 print(arr.size)

20


In [6]:
print(arr.dtype)

int64


In [7]:
print(arr.ndim)

2


In [18]:
#type casting
# Method - 1
arr = np.full((3, 5), 9, dtype="U5")

print(arr, arr.dtype)

# Method - 2

new_arr = arr.astype(np.float64)
print(new_arr, new_arr.dtype)

[['9' '9' '9' '9' '9']
 ['9' '9' '9' '9' '9']
 ['9' '9' '9' '9' '9']] <U5
[[9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]] float64


In [17]:
arr = np.array([1, 3.5, 6])

print(arr, arr.dtype)

[1.  3.5 6. ] float64
