In [1]:
# 7. Reshaping Arrays

In [2]:
import numpy as np

In [18]:
arr = np.array(([1, 3], [5, 7], [9, 11]))

print(arr, arr.shape)

print(arr.reshape(2, 3), arr.reshape(2, 3).shape)

print(arr.flatten())

[[ 1  3]
 [ 5  7]
 [ 9 11]] (3, 2)
[[ 1  3  5]
 [ 7  9 11]] (2, 3)
[ 1  3  5  7  9 11]
