In [1]:
# 8. Indexing on Arrays

In [2]:
import numpy as np

In [3]:
arr = np.array(([1,2,3,4,5], [6,7,8,9,10]))

print(arr, arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)


In [8]:
print(arr[1][4])

10


In [11]:
# fancy Indexing
newArr = arr.flatten()
print(newArr)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
idx = [2, 3, 0, 5]

print(newArr[[idx]])

[[3 4 1 6]]


In [27]:
# Boolean Indexing
print(newArr[newArr >= 8])
print(newArr[newArr/2 >= 3])

[ 8  9 10]
[ 6  7  8  9 10]
