In [1]:
# 9. Slicing Arrays

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
print(arr[1: 10: 3])
print(arr[1:])
print(arr[: 10])
print(arr[::3])

[2 5 8]
[ 2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]
