In [1]:
# 11. Common Numpy Data Types

In [2]:
import numpy as np

In [3]:
# Integers
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr, arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10] int64


In [4]:
# Floating Point
arr = np.array([1,2,3,4,5,6,7,8,9.3,10])

print(arr, arr.dtype)

[ 1.   2.   3.   4.   5.   6.   7.   8.   9.3 10. ] float64


In [5]:
# Downcasting
arr = np.array([1,2,3,4,5,6,7,8,9,10], dtype="int8")

print(arr, arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10] int8


In [7]:
# bool
arr = np.array([1,2,3,4,5,6,7,8,9,10, True])

print(arr, arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10  1] int64


In [12]:
# Complex Numbers

arr1 = np.array([4 + 6j])
arr2 = np.array([8 +2j])

print(arr1+arr2, (arr1+arr2).dtype)

print(arr, arr.dtype)

[12.+8.j] complex128
[4.+6.j 8.+2.j] complex128


In [6]:
# String
arr = np.array([1,2,3,4,5,6,7,8,9,10, "Cipher Mind"])

print(arr, arr.dtype)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' 'Cipher Mind'] <U21


In [14]:
# Object
arr = np.array(["Python", {1,2,3}, 7])

print(arr, arr.dtype)

['Python' {1, 2, 3} 7] object
