In [1]:
# 12. Multi-dimensional Arrays & Axes

In [2]:
import numpy as np

In [3]:
arr1D = np.array([1,3,5])

print(arr1D)

[1 3 5]


In [10]:
arr2D = np.array([[1,3,5], [2,7,1], [1,5,7]])

print(arr2D)

print(f"Sum of all Elements: {np.sum(arr2D)}")
print(f"Sum of all vertical Elements: {np.sum(arr2D, axis=0)}")
print(f"Sum of all horizontal Elements: {np.sum(arr2D, axis=1)}")

[[1 3 5]
 [2 7 1]
 [1 5 7]]
Sum of all Elements: 32
Sum of all vertical Elements: [ 4 15 13]
Sum of all horizontal Elements: [ 9 10 13]


In [12]:
# Slicing in 2D Arrays
print(arr2D[0:2, 1:2])

[[3]
 [7]]
