In [1]:
# 13. 3D Arrays

In [2]:
import numpy as np

In [10]:
arr3D = np.array([[[2, 5, 3], [1, 7, 9], [8, 2, 6]],[[1, 5, 8], [3, 2, 0], [8, 6, 3]],[[8, 1, 4], [2, 9, 9], [5, 1, 7]]])

print(arr3D)

print(arr3D[1, 2, 0])

print(arr3D.shape)

print(f"Sum of elements: {np.sum(arr3D)}")

arr3D[0, 0:1, 0:2] = 99

print(f"Slicing Example: {arr3D[0, 0:1, 0:2]}")

[[[2 5 3]
  [1 7 9]
  [8 2 6]]

 [[1 5 8]
  [3 2 0]
  [8 6 3]]

 [[8 1 4]
  [2 9 9]
  [5 1 7]]]
8
(3, 3, 3)
Sum of elements: 125
Slicing Example: [[99 99]]
