In [1]:
# 14. Vectorization & Broadcasting

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [5]:
print(arr, type(arr))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [6]:
# Vectorization
print(arr**2)

[  1   4   9  16  25  36  49  64  81 100]


In [7]:
print((arr**2) + arr)

[  2   6  12  20  30  42  56  72  90 110]


In [8]:
# Broadcasting
print(arr + 5)

[ 6  7  8  9 10 11 12 13 14 15]


In [10]:
arr2 = np.array(1)

print(arr+arr2)

[ 2  3  4  5  6  7  8  9 10 11]
