In [1]:
# 17. Mathematical Functions (Aggregate)

In [2]:
import numpy as np

In [3]:
 # Aggregation
arr = np.array([1, 3, 5, 7, 3, 9])

print(arr)
print(f"Sum(): {np.sum(arr)}")
print(f"Prod(): {np.prod(arr)}")
print(f"Min(): {np.min(arr)}")
print(f"Max(): {np.max(arr)}")
print(f"Mean(): {np.mean(arr)}")
print(f"Standard Deviation(): {np.std(arr)}")
print(f"Variance(): {np.var(arr)}")
print(f"Median(): {np.median(arr)}")
print(f"Argmin(): {np.argmin(arr)}")
print(f"Argmax(): {np.argmax(arr)}")

[1 3 5 7 3 9]
Sum(): 28
Prod(): 2835
Min(): 1
Max(): 9
Mean(): 4.666666666666667
Standard Deviation(): 2.6874192494328497
Variance(): 7.222222222222221
Median(): 4.0
Argmin(): 0
Argmax(): 5


In [4]:
# Power
print(arr)
print(f"Square(): {np.square(arr)}")
print(f"SQRT(): {np.sqrt(arr)}")
print(f"Pow(): {np.pow(arr, 3)}")

[1 3 5 7 3 9]
Square(): [ 1  9 25 49  9 81]
SQRT(): [1.         1.73205081 2.23606798 2.64575131 1.73205081 3.        ]
Pow(): [  1  27 125 343  27 729]


In [5]:
# Rounding
print(arr)
print(f"Round(): {np.round(np.sqrt(arr))}")
print(f"Floor(): {np.floor(np.sqrt(arr))}")
print(f"Ceil(): {np.ceil(np.sqrt(arr))}")
print(f"Trunc(): {np.trunc(np.sqrt(arr))}")

[1 3 5 7 3 9]
Round(): [1. 2. 2. 3. 2. 3.]
Floor(): [1. 1. 2. 2. 1. 3.]
Ceil(): [1. 2. 3. 3. 2. 3.]
Trunc(): [1. 1. 2. 2. 1. 3.]


In [6]:
# Log & Exponential
print(arr)
print(f"Log(): {np.log(arr)}")
print(f"Log10(): {np.log10(arr)}")
print(f"Log2(): {np.log2(arr)}")
print(f"Exp(): {np.exp(arr)}")

[1 3 5 7 3 9]
Log(): [0.         1.09861229 1.60943791 1.94591015 1.09861229 2.19722458]
Log10(): [0.         0.47712125 0.69897    0.84509804 0.47712125 0.95424251]
Log2(): [0.         1.5849625  2.32192809 2.80735492 1.5849625  3.169925  ]
Exp(): [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 2.00855369e+01 8.10308393e+03]
